### ISSUE TITLE
System: warning about high CPU temperature is monitoring CPU use instead of cpu_temp

### ISSUE THREAD

**Issue by gabrio79** [basnijholt/home-assistant-config#12]
- alias: "System: warning about high CPU temperature"
  trigger:
    platform: numeric_state
    entity_id: sensor.processor_use
    above: 70
    for:
      hours: 4
  action:
    service: notify.mobile_app_basnijholt_iphone
    data:
      title: "System"
      message: "CPU temperature has been above 70 °C for 4 hours! ⚠️"

**Comment by basnijholt** [comment]
Thanks a lot for telling me! Coincidentally, I had just noticed this myself earlier today.

**Comment by basnijholt** [comment]
Fixed in https://github.com/basnijholt/home-assistant-config/commit/690a89a47cbc3779b253fdc49fe145c9fcbf9b12.
