### ISSUE TITLE
input select needs an update

### ISSUE THREAD

**Issue by L1cardo** [basnijholt/home-assistant-config#26]
The "select theme" action has been broken due to 87197a46e9db3a7fd566278fbdfc6f076a767a44.
Can you update files https://github.com/basnijholt/home-assistant-config/blob/master/includes/input_selects.yaml and https://github.com/basnijholt/home-assistant-config/blob/master/includes/input_booleans.yaml please ?

**Comment by basnijholt** [comment]
Ah, that is because I am using the code from this PR https://github.com/basnijholt/lovelace-ios-themes/pull/26

**Comment by basnijholt** [comment]
I have reverted the behavior. My code should work again :)
