### ISSUE TITLE
lights_on_total_hours question

### ISSUE THREAD

**Issue by MrThiemann** [basnijholt/home-assistant-config#27]
Hey first of all, many thanks for the publication of your script! it is great! Especially at the beginning it is nice if you can get ideas and suggestions here.

but i have a question about your lights_on_total_hours.
you enter different float for the different states here ?!? can you explain to me why that is?

````
    lights_on_total_hours:
      unit_of_measurement: h
      value_template: >
        {{ states('sensor.hours_bedroom_lights_have_been_on_last_7_days')|float * 7
            + states('sensor.hours_living_room_lights_have_been_on_last_7_days')|float * 5
            + states('sensor.hours_toilet_light_has_been_on_last_7_days')|float * 1
            + states('sensor.hours_bathroom_light_has_been_on_last_7_days')|float * 1
            + states('sensor.hours_kitchen_lights_have_been_on_last_7_days')|float * 2
            + states('sensor.hours_hall_lights_have_been_on_last_7_days')|float * 5
            + states('sensor.hours_bathroom_light_has_been_on_last_7_days')|float * 1 }}
````

in the part where you add up the total costs, I am also a little surprised. 
As an entity you have specified "hours_bathroom_light_has_been_on_last_7_days".
are you doing this on purpose? so that you have a close look at the code and not just copy your script? ;)

````
- entity: sensor.hours_bathroom_light_has_been_on_last_7_days
      icon: mdi:clock
      name: Total cost estimate for last 7 days
      secondary: 'Total is {{ states(''sensor.lights_on_total_hours'') | round(1)
        }} hours, {{ states(''sensor.lights_on_total_kwh'') | round(1) }} kWh, €{{
        (states(''sensor.lights_on_total_kwh'')|float * 0.21) | round(2) }}.
        '
      state: '{{ states("sensor.hours_bathroom_light_has_been_on_last_7_days") }}
        h'
      type: custom:template-entity-row
    title: Lights on last 7 days
    type: entities
````

I have included 2 of my entities for the time being. one lamp was on for 1.26 h in the last 7 days. The other 8.08h

However, total coast has a value of 49.22 hours. but that doesn't work with the two lamps ?! Does that have something to do with the float values?

**Comment by tmttn** [comment]
Looks like the float value is the number of physical lamps in each room.

**Comment by basnijholt** [comment]
@MrThiemann, it is like @tmttn says, it's the number of lights in the room :)

**Comment by basnijholt** [comment]
Let me know whether it's still unclear and I will reopen this issue.
