### ISSUE TITLE
Quick fix for failing '0m' in hours outside sensor

### ISSUE THREAD

**Issue by metbril** [basnijholt/home-assistant-config#32]
I've implemented a quick fix for your issue that the hours outside sensor doesn't work with '0m'.
It does never work when the value has less than 3 arguments. I've added some dummy arguments if there are too few.

Just a quick hack. This can be programmed more efficiently, I guess.
That's why I haven't send a PR.

https://github.com/basnijholt/home-assistant-config/blob/ae69265f1b9bb904e884e985b99d5d2cbaa77f82/includes/sensors.yaml#L254

The fix:

```yaml
    hours_outside_per_day_marcella: # XXX: fails when returns "0m"
      friendly_name: Ten minutes before alarm
      value_template: >
        {% set value = state_attr("sensor.quarantine_meter_marcella", "value") %}
        {% if value != None %}

        {# ----- start fix ----- #}
        {% set args = 1 + (value | length) - (value.replace(' ', '') | length) %}
        {% if args < 2 %}
        {% set value = "0h " ~ value %}
        {% endif %}
        {% if args < 3 %}
        {% set value = "0d " ~ value %}
        {% endif %}
        {# ----- end fix ----- #}

        {% set d, h, m = value.split() %}
        {% set d, h, m = d[:-1] | int, h[:-1] | int, m[:-1] | int %}
        {% set hours_outside = ((14 - d) * 86400 - h * 3600 - m * 60) / 3600 %}
        {{ (hours_outside / 14) | round(1) }}
        {% endif %}
```

**Comment by basnijholt** [comment]
This is great! I have been out of the HA game for a couple of months.

What does the `~ value` do?

**Comment by basnijholt** [comment]
This is great! I have been out of the HA game for a couple of months.

I have implemented your fix in https://github.com/basnijholt/home-assistant-config/commit/0545db95ef7c3b2c6848d7919513dd31a96e275a
