### ISSUE TITLE
Apple Watch Set lights

### ISSUE THREAD

**Issue by hwikene** [basnijholt/home-assistant-config#33]
Hi! Not sure if you use this anymore? But i cant get this action to work after there have been some change in the HA IOS APP. 
Does your work?

**Comment by arsaboo** [comment]
Seeing the same issue....commenting to follow the update.

**Comment by hwikene** [comment]
Sweet!! I will test it out later 👍

**Comment by basnijholt** [comment]
I have updated my code in this commit: https://github.com/basnijholt/home-assistant-config/commit/2cde67d1a67f7b8fef5f24c94af02d4581cebd83

I have tested it, it works :)
