### ISSUE TITLE
Remove Push from iOS:

### ISSUE THREAD

**Issue by jokerigno** [basnijholt/home-assistant-config#35]
Hi,

I came here from your reddit post made 2 years ago,

I just want you to notice that starting from 2022.04 the "push" option is deprecated and it have to be removed from the iOS integration.

Please see the message below:

_"WARNING:homeassistant.components.ios:The 'push' option is deprecated, please remove it from your configuration"_

You will update your automations accordly?

Moreover did you upgraded some of the action from AW? You already helped me so much but I was wondering if you have some other userful thing to share :)

Thank you

**Comment by basnijholt** [comment]
Hi there, I just moved and was without HA for 4 months.

I just fixed this: https://github.com/basnijholt/home-assistant-config/commit/2cde67d1a67f7b8fef5f24c94af02d4581cebd83

I don't really like this new way. I will try to reduce the boilerplate later.
