### ISSUE TITLE
Fix from #32 literally prints "# Fix from https://github.com/..."

### ISSUE THREAD

**Issue by tmttn** [basnijholt/home-assistant-config#36]
The comments from #32 added in the `value_template` of `hours_outside_per_day_*` in `sensors.yaml` are considered as part of the template value:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1706040/164426819-b3d94238-fe00-49da-ab65-51fb9baeaf3e.png">

**Comment by basnijholt** [comment]
Thanks for noting. I only added the comment after testing :)
