### ISSUE TITLE
Custom element doesn't exist: hui-entity-button-entity-row.

### ISSUE THREAD

**Issue by Reznorzo** [basnijholt/home-assistant-config#4]
Hi Bas,
I hope you're well.
I've been using your lovelace config as a basis for mine. Was working fine up until a couple of days ago, and now on the lights stack I'm getting the following:
Custom element doesn't exist: hui-entity-button-entity-row.

Any ideas ?

**Comment by basnijholt** [comment]
I have just noticed this myself too, I will investigate and post the solution here when I have time.

**Comment by basnijholt** [comment]
@Reznorzo, just remove the line `type:`.

I have fixed it in my config.

Reopen if that doesn't fix it for you!

**Comment by Reznorzo** [comment]
@basnijholt Cheers Bas. Yes, that worked thanks.
Any idea what caused the change ?

And keep up the good work !
